config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  delete 'destroy_session', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create]
  resources :users, only: [:new]
  post '/users/new', to: 'users#create'

  post 'message',to: 'messages#create'
  mount ActionCable.server, at:'/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true, length:{minimum:1, maximum: 200}

    scope :last_ten, -> { order(:created_at).limit(10)}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :messages
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length:{minimum:4, maximum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
           flash[:error] = "You have to sign in first to perform this action"
           redirect_to new_session_path
        end
    end
end

app/controllers/messages_controller.rb
require 'format_string'
class MessagesController < ApplicationController
    include FormatString
    before_action :require_user
    def create
        message = current_user.messages.build(message_params)
        if message.save
            ActionCable.server.broadcast "chatroom_channel", 
                                            {mod_message: message_render(FormatString.upper message)}
        end
    end

    private
    def message_params
        params.require(:message).permit(:body)
    end

    def message_render(message)
        render(partial: 'message', locals: {message: message})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :require_user, only:[:home]

    def home
        @message = Message.new
        @messages = Message.last_ten
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in_redirect, only: [:new, :create]
    def new
    end

    def create
        user = User.find_by_username(session_params[:username])
        if user and user.authenticate(session_params[:password])
            session[:user_id] = user.id
            flash[:success] = "Welcome to Chatify"
            redirect_to root_path
        else
            flash[:error] = "Your credentials are not valid, please check you username/password and try again"
            render "new"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to new_session_path, status: :see_other
    end

    private 
    def session_params
        params.require(:session).permit(:username,:password)
    end

    def logged_in_redirect
        if logged_in?
            flash[:error] = "You are already logged in"
            redirect_to root_path, status: :see_other
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render "users/new"
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to chatify"
            redirect_to root_path
        else
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:username,:password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div class="ui error message">
        <i class="close icon"></i>
        <div class="header">
            The following errors prevented the <%= object.class.name.downcase %> from being saved
        </div>
        <ul class="list">
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>  

app/views/layouts/_flash.html.erb
<% flash.each do |name,message| 
    if name == "success"
        message_type = "positive "
    elsif name == "alert"
        message_type = "warning"
    else 
        message_type = "negative"
    end
    %>
    <div class="ui <%= message_type %> message">
        <i class="close icon"></i>
        <div class="header">
            <%= message %>
        </div>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="ui small menu inverted">
    <div class="ui container">
        <%= link_to  "Chat room", root_path, class: "active item"%>
        <div class="right menu">
            <div class="ui dropdown item">
            
            <%= @current_user ? @current_user.username : "Account" %> <i class="dropdown icon"></i>
            <div class="menu">
                <%= (link_to  "Log out", destroy_session_path, data: { turbo_method: :delete }, class: "item" ) if logged_in? %>
                <%= (link_to  "Log in", new_session_path, class: "item")  if !logged_in? %>
            </div>
            </div>
            <div class="item">
                <% if !logged_in? %>
                    <%= link_to "Sign Up", users_new_path, class: 'ui purple button' %>
                <% end %>
            </div>
        </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatify</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "custom", media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>

    <%= render "layouts/navbar" %>
    <div class="ui container">
    <%= render "layouts/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
    <div class="summary">
        <em class="pruple"><%= message.user.username %>:</em> <%= message.body %>
    </div>
    </div>
</div>

app/views/pages/home.html.erb
<h1 class="ui center aligned icon header ">
  <i class="circular chat icon purple "></i>
  Say Something
</h1>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content" id="messages-feed">
                <div class="ui feed" id="chat-feed">
                    <h4 class="ui header" >Chat Feed</h4>
                    <%  @messages.each {|message| %>
                        <%= render message %>
                    <% } %>
                </div>
            </div>
            <div class="extra content">
                <%= form_for(@message, html: {class:"ui reply form", role:"form"}, url: message_path, data: {turbolinks: false}) do |f| %>
                    <div class="field">
                        <div class="ui fluid icon input">
                            <%= f.text_field :body, placeholder: "Enter a message..." %>
                            <%= f.button '<i class="bordered inverted purple edit icon"></i>'.html_safe %>
                            
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    <div class="four wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui secondary vertical pointing menu ">
                    <a class="active item">
                        Home
                    </a>
                    <a class="item">
                        Messages
                    </a>
                    <a class="item">
                        Friends
                    </a>
                </div>  
            </div>  
        </div>  
    </div>
</div>

app/views/users/new.html.erb
<h3 class="ui center aligned header">
  Welcome to Chatify - a demo of using sockets by Abner del Cid
</h3>
<h2 class="ui center aligned icon header">
  <i class="circular user plus purple icon"></i>
</h2>


<%= render "layouts/errors", object: @user  %>
<div class="ui placeholder segment">
    <div class="ui column ">
        <div class="column">
            <div class="ui form">
                
                <%= form_for @user,url: users_new_path,class:"ui form", local: true, data: { turbo: false, turbo_method: :post} do |f| %>
                    <div class="field">
                    <label>Username</label>
                    <div class="ui left icon input">
                    <%= f.text_field :username, class:"form-control shadow", placeholder:"Type your username" %>
                        <i class="user icon"></i>
                    </div>
                    </div>
                    <div class="field">
                    <label>Password</label>
                    <div class="ui left icon input">
                    <%= f.password_field :password, class:"form-control shadow", placeholder:"Type your password" %>
                        <i class="lock icon"></i>
                    </div>
                    </div>
                    <%= f.submit "Sign Up", class: "ui purple submit button" %>
                <% end %>
            </div>
        </div>
    </div>
</div>